image:
  name: spvboib/22:custom
  username: spvboib
  password: iMhotep&2500

pipelines:
  default:
    - step:
        runs-on: self.hosted # die wichtigste Zeile, notwendig bei jedem 'step'
        name: e2e Tests (testcafe)
        script:
          - npm install
          - testcafe --config-file tests/front-end/testcaferc.json --no-sandbox --disable-dev-shm-usage --disable-setuid-sandbox tests/front-end/e2e-login.ts
    - step:
        runs-on: self.hosted # die wichtigste Zeile, notwendig bei jedem 'step'
        name: API Tests (pytest)
        script:
          - pip install -r requirements.txt
          - pytest -v --junitxml=test-results/report.xml -s