image: python:3.9-slim

pipelines:
  default:
    - step:
        runs-on: self.hosted # die wichtigste Zeile, notwendig bei jedem 'step'
        name: API Tests
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - apt-get -y install libpq-dev python3-dev gcc
          - pip install psycopg2
          - pytest -v --junitxml=test-results/report.xml -s