# This Dockerfile builds the React front end for nginx.
# It also proxies /api requests to api:5000

# Build step #1: build the React front end
FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

# ENV PREACT_APP_HOST_URI https://biobanding.azurewebsites.net
ENV PREACT_APP_HOST_URI http://localhost
ENV PREACT_APP_VERSION v1.0.0
ENV PREACT_APP_IMPRESSUM https://www.vflastrostars.de/verein/kontakt-footer/impressum-footer
ENV PREACT_APP_DSGVO  https://www.vflastrostars.de/verein/images/download/Einwilligungserklrung_Bio-Banding.pdf

COPY package.json yarn.lock ./
COPY preact.config.js preact.config.js
COPY ./src ./src
RUN yarn install
RUN yarn build --no-prerender

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY nginx/dev.conf /etc/nginx/conf.d/default.conf