services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: rest-api
    restart: unless-stopped
    container_name: api
    environment:
      - FLASK_ENV=production
    ports:
      - 5000

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: rest-client
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - api
    container_name: client

 