FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get -y install cron libpq-dev python3-dev gcc

COPY ./api ./api
COPY requirements.txt ./
COPY run.py ./
COPY .flaskenv ./

# Define etrypoint for crontab
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


# Copy my-cron file to the my-cron.d directory
COPY my-cron /etc/cron.d/my-cron

# Give execution rights on the my-cron job
RUN chmod 0644 /etc/cron.d/my-cron

# Apply my-cron job
RUN crontab /etc/cron.d/my-cron

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

#ENV PREACT_APP_HOST_URI https://biobanding.azurewebsites.net
ENV PREACT_APP_HOST_URI http://localhost

RUN pip install -r requirements.txt

ENTRYPOINT ["/entrypoint.sh"]
