FROM python:3.9-slim

WORKDIR /app

COPY ./api ./api
COPY requirements.txt ./
COPY run.py ./

ENV PREACT_APP_HOST_URI http://0.0.0.0

RUN pip install -r requirements.txt

CMD gunicorn -b 0.0.0.0:5000 run:app