# This Dockerfile builds the React front end for nginx.
# It also proxies /api requests to api:5000

# Build step #1: build the React front end
FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV PREACT_APP_HOST_URI http://0.0.0.0
ENV PREACT_APP_VERSION 1.0
COPY package.json yarn.lock ./
COPY preact.config.js preact.config.js
COPY ./src ./src
RUN yarn install
RUN yarn build --no-prerender

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY nginx/dev.conf /etc/nginx/conf.d/default.conf