services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: biobanding.azurecr.io/api
    restart: unless-stopped
    container_name: api
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
    ports:
      - 5000

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: biobanding.azurecr.io/client
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - api
    container_name: client



 