CREATE TABLE PLAYER_MASTER (
	fk_user_id INTEGER NOT NULL,
	first_name varchar(64),
	last_name varchar(64), 
	PRIMARY KEY (fk_user_id)
);

CREATE TABLE PLAYER_DETAIL (
	ID INTEGER,
	FK_USER INTEGER,
	TEXT_OF_BIRTH TEXT,
	SEX_M_0_F_1 INTEGER,
	HEIGHT_FATHER INTEGER,
	HEIGHT_MOTHER INTEGER
);

CREATE TABLE ANTHROPOMETRIC_DATA (
	ID INTEGER,
	FK_USER INTEGER,
	ENRY_TEXT TEXT,
	HEIGHT INTEGER,
	SITTING_HEIGHT INTEGER,
	WEIGHT INTEGER,
	BODY_SPAN INTEGER,
	RESULT REAL
);	

CREATE TABLE users (
	id INTEGER NOT NULL, 
	username VARCHAR(32) NOT NULL, 
	email VARCHAR(64) NOT NULL, 
	password TEXT, 
	jwt_auth_active BOOLEAN, 
	date_joined DATETIME, 
	PRIMARY KEY (id)
)

CREATE TABLE ADMIN_CONFIG (
	ID INTEGER,
	REMINDER_DAYS INTEGER
);
