CREATE TABLE PLAYER_MASTER (
	ID INTEGER,
	FIRST_NAME TEXT,
	LAST_NAME TEXT
);

CREATE TABLE PLAYER_DETAIL (
	ID INTEGER,
	FK_PLAYER INTEGER,
	TEXT_OF_BIRTH TEXT,
	SEX_M_0_F_1 INTEGER,
	HEIGHT_FATHER INTEGER,
	HEIGHT_MOTHER INTEGER
);

CREATE TABLE ANTHROPOMETRIC_DATA (
	ID INTEGER,
	FK_PLAYER INTEGER,
	ENRY_TEXT TEXT,
	HEIGHT INTEGER,
	SITTING_HEIGHT INTEGER,
	WEIGHT INTEGER,
	BODY_SPAN INTEGER,
	RESULT REAL
);	

CREATE TABLE APP_USER (
	ID INTEGER,
	FK_PLAYER INTEGER,
	USER_NAME TEXT,
	PASSWORD TEXT,
	EMAIL_ADDRESS TEXT,
	IS_ACTIVE INTEGER,
	IS_ADMIN INTEGER
);